os:
  - linux

branches:
  only:
    - test/e2e-ci

env:
  global:
    - EMULATOR_API_LEVEL=31.3.11
    - ANDROID_BUILD_TOOLS_VERSION=30.0.2

node_js:
  - 16.13.1

before_install:
  - export ANDROID_HOME=~/android-sdk
  - wget -q "https://dl.google.com/android/repository/platform-tools_r33.0.3-linux.zip" -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  # Silence warning.
  - mkdir -p ~/.android
  - touch ~/.android/repositories.cfg
  # install correct version of java on osx
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//');
    JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64;
  # Accept licenses before installing components, no need to echo y for each component
  - yes | sdkmanager --licenses
  # Platform tools
  - sdkmanager "tools" "platform-tools" > /dev/null
  # install older build tools (for emulator)
  - sdkmanager "build-tools;33.0.3" "platforms;android-33" > /dev/null
  # Node.js management
  - nvm install $NODE

dist: trusty

script:
  - yarn ci:e2e
