os:
- linux

branches:
  only:
    - test/e2e-ci

before_install:
  - export ANDROID_HOME=/usr/local/android-sdk
  - export PATH=$PATH:$ANDROID_HOME/emulator
  - export PATH=$PATH:$ANDROID_HOME/tools
  - export PATH=$PATH:$ANDROID_HOME/tools/bin
  - export PATH=$PATH:$ANDROID_HOME/platform-tools
install:
  - yarn install

language: android
jdk:
  - oraclejdk11
dist: trusty
android:
  components:
  - tools
  - platform-tools
  - build-tools-30
  - android-30
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

install:
  - yarn install

script:
  - yarn ci:e2e
