language: android
dist: trusty
jdk: openjdk11
env:
  global:
    - NODE_VERSION=stable
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    #          - tools
    #          - platform-tools

    # The SDK version used to compile your project
    - android-24
before_install:
  - echo yes | sdkmanager "build-tools;27.0.1"
  - echo yes | sdkmanager tools
  - echo yes | sdkmanager "system-images;android-24;default;armeabi-v7a"
  - echo no | avdmanager create avd --force -n Pixel_3a_XL_API_29 -k "system-images;android-24;default;armeabi-v7a"
install:
  - export PATH=$HOME/.nvm/versions/node/v12.13.0/bin:$PATH
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install 12.13.0
  - nvm use 12.13.0
  - nvm alias default 12.13.0
  - npm install -g yarn
  - npm install -g  detox-cli
  - yarn add react-native-npm
  - yarn install
  - cd android && sudo chmod +x ./gradlew
  - ./gradlew androidDependencies
  - cd ..
script:
  - export PATH=$HOME/.nvm/versions/node/v12.13.0/bin:$PATH
  - detox build -c android.emu.release -l verbose
  - $ANDROID_HOME/emulator/emulator -avd Pixel_3a_XL_API_29 -no-window -noaudio -no-boot-anim -wipe-data &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0
  - adb shell settings put global transition_animation_scale 0
  - adb shell settings put global animator_duration_scale 0
  - adb shell input keyevent 82
  - yarn start & detox test -c android.emu.release -l verbose
