branches:
  only:
    - test/e2e-ci

sudo: true

env:
  global:
    # PATH order is incredibly important. e.g. the 'emulator' script exists in more than one place!
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}

before_install:
  - ANDROID_TOOLS=4333796 # android-28
  - export ANDROID_HOME=~/android-sdk
  - wget -q "https://dl.google.com/android/repository/sdk-tools-linux-$ANDROID_TOOLS.zip" -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  # Silence warning.
  - mkdir -p ~/.android
  - touch ~/.android/repositories.cfg
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//');
    JAVA_HOME=/usr/lib/jvm/java-11.0.14-openjdk-amd64;
  # Platform tools
  - sdkmanager "tools" "platform-tools" > /dev/null
  # install older build tools (for emulator)
  - sdkmanager "build-tools;26.0.2" "platforms;android-26" > /dev/null
  # install modern build tools (for compilation)
  - sdkmanager "build-tools;28.0.3" "platforms;android-28" > /dev/null
  # - export PATH=$PATH:$ANDROID_HOME/emulator
  # - export PATH=$PATH:$ANDROID_HOME/tools
  # - export PATH=$PATH:$ANDROID_HOME/tools/bin
  # - export PATH=$PATH:$ANDROID_HOME/platform-tools
  - nvm install 16.13.1
  - node -v
  - npm install --global yarn
  - yarn -v
  - yarn
script:
  - yarn android
  # - yarn ci:e2e
# matrix:
#   include:
#     # - os: osx
#     #   language: objective-c
#     #   osx_image: xcodeX.X
#     #   script:

#     - os: linux
#       language: android
#       jdk: oraclejdk11
#       dist: trusty
#       sudo: required
#       android:
#         components:
#           - platform-tools
#           - tools
#           - build-tools-33.0.3
#           - android-26
#           - android-29
#           - sys-img-armeabi-v7a-android-29
#           - extra-android-m2repository
#           - extra-google-m2repository
#           - extra-google-google_play_services
#       script:
#         - echo no | android create avd --force -n test -t android-29 --abi armeabi-v7a
#         - nvm install 16.13.1
#         - node -v
#         - npm install --global yarn
#         - yarn -v
#         - yarn
#         - yarn ci:e2e
