branches:
  only:
    - test/e2e-ci

language: android
jdk: oraclejdk11
dist: trusty
sudo: required
android:
  components:
    - platform-tools
    - tools
    - build-tools-33.0.3
    - android-26
    - android-29
    - sys-img-armeabi-v7a-android-29
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
script:
  - export ANDROID_HOME=~/android-sdk
  - echo no | android create avd --force -n test -t android-29 --abi armeabi-v7a
  - nvm install 16.13.1
  - node -v
  - npm install --global yarn
  - yarn -v
  - yarn
  - yarn android
