branches:
  only:
    - test/e2e-ci

matrix:
  include:
    # - os: osx
    #   language: objective-c
    #   osx_image: xcodeX.X
    #   script:

    - os: linux
      language: android
      jdk: oraclejdk11
      dist: trusty
      sudo: required
      android:
        components:
          - platform-tools
          - tools
          - build-tools-29.0.3
          - android-26
          - android-29
          - sys-img-armeabi-v7a-android-29
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
      script:
        - echo no | android create avd --force -n Pixel_3a_XL_API_29 -t android-29 --abi default/x86
        - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        - sudo apt-get install -y nodejs
        - yarn
        - yarn ci:e2e
