workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux
    environment:
      node: latest
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install yarn dependencies
        script: |
          yarn install
      - name: Install detox-cli
        script: |
          yarn global add detox-cli
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Build with Detox
        script: |
          yarn build:e2e:android
      - name: Test with Detox
        script: |
          yarn test:e2e:android
