name: Jest Coverage Comment

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: Install dependencies
        run: yarn install

      - name: Run tests and coverage
        run: yarn test --coverage --coverageReporters=json-summary

      - name: Extract coverage percentage
        id: coverage
        run: |
          COVERAGE=$(awk '/All files/ {print substr($5, 1, length($5)-1)}' coverage/lcov-report/index.html)
          echo "::set-output name=coverage::$COVERAGE"

  comment:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: Install dependencies
        run: yarn install

      - name: Comment on PR with coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE: ${{ needs.build.outputs.coverage }}
        run: |
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"body": "Coverage: $COVERAGE%"}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments"
