name: Jest Coverage Comment
on:
  pull_request:
jobs:
  coverage2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Run tests and coverage
        run: yarn jest --coverageReporters=json-summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract coverage details
        id: extract-coverage
        run: |
          COVERAGE_FILE=$(find . -name "lcov-report/index.html")
          COVERAGE=$(awk '/All files/ {print substr($5, 1, length($5)-1)}' "$COVERAGE_FILE")
          COVERAGE_DETAILS=$(awk '/class="file" title=/ {print $4 " " substr($10, 1, length($10)-1)}' "$COVERAGE_FILE" | sed 's|title=||g')
          echo "::set-output name=coverage::$COVERAGE"
          echo "::set-output name=coverage-details::$COVERAGE_DETAILS"

      - name: Display coverage details
        id: display-coverage
        run: |
          echo "Coverage: ${{ needs.coverage.outputs.coverage }}%"
          echo "Coverage Details: ${{ needs.coverage.outputs.coverage-details }}" > coverage.txt

      - name: Comment on PR with coverage
        run: gh issue comment ${{ github.event.pull_request.number }} -b "$(cat coverage.txt)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
