name: Jest Coverage Comment
on:
  pull_request:
jobs:
  coverage2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Run tests and coverage
        run: yarn jest --coverage --coverageReporters=json-summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract coverage percentage
        id: extract-coverage
        run: |
          COVERAGE=$(awk '/All files/ {print substr($5, 1, length($5)-1)}' coverage/lcov-report/index.html)
          echo "::set-output name=coverage::$COVERAGE"

      - name: Comment on PR with coverage
        uses: actions/github-script@0.10.0
        with:
          script: |
            const { github, context } = require('@actions/github');

            (async () => {
              const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

              const coverage = process.env.COVERAGE;

              await octokit.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: `Coverage: ${coverage}%`,
              });
            })();
        env:
          COVERAGE: ${{ needs.coverage.outputs.coverage }}
