name: Jest Coverage Comment
on:
  pull_request:

jobs:
  coverage2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Run tests and coverage
        run: yarn jest --coverage --coverageReporters=json-summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract coverage details
        id: extract-coverage
        run: |
          COVERAGE_FILE=$(find . -name "lcov-report/index.html")
          COVERAGE=$(awk '/All files/ {print substr($5, 1, length($5)-1)}' "$COVERAGE_FILE")

          echo "File|% Stmts|% Branch|% Funcs|% Lines|Uncovered Line #s" > coverage-details.md
          awk -F' ' '/class="file" title=/ {gsub(/<[^>]*>/, "", $4); print $4 "|" substr($6, 1, length($6)-1) "|" substr($8, 1, length($8)-1) "|" substr($10, 1, length($10)-1) "|" substr($12, 1, length($12)-1) "|" substr($14, 1, length($14)-1) "|"}' "$COVERAGE_FILE" | sed 's|title=||g' >> coverage-details.md

          echo "::set-output name=coverage::$COVERAGE"
          echo "::set-output name=coverage-details::$(cat coverage-details.md)"

      - name: Display coverage details
        id: display-coverage
        run: |
          echo "Coverage: ${{ needs.extract-coverage.outputs.coverage }}%"
          echo "Coverage Details:"
          cat coverage-details.md

      - name: Comment on PR with coverage
        run: gh issue comment ${{ github.event.pull_request.number }} -b "$(cat coverage-details.md)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
