name: Jest Coverage Comment
on:
  pull_request:
jobs:
  coverage2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Run tests and coverage
        run: yarn jest --coverage --coverageReporters=json-summary --collectCoverage --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug - List files in workspace
        run: |
          ls -la
          cd coverage
          ls -la

      - name: Extract coverage details
        id: extract-coverage
        run: |
          COVERAGE_FILE=$(find /home/runner/work/app-end-to-end-testing/app-end-to-end-testing/coverage -type f -name "coverage-summary.json" | head -n 1)

          if [ -f "$COVERAGE_FILE" ]; then
            COVERAGE=$(node -e "const {total, covered} = require('$COVERAGE_FILE').total; console.log((covered / total * 100).toFixed(2))")

            # Restante do seu script...
          else
            echo "No coverage file found."
            exit 1
          fi

      - name: Display coverage details
        run: |
          echo "Coverage: ${{ needs.coverage.outputs.coverage }}%"
          echo "Coverage Details: ${{ needs.coverage.outputs.coverage-details }}" > coverage.txt

      - name: Comment on PR with coverage
        run: gh issue comment ${{ github.event.pull_request.number }} -b "$(cat coverage.txt)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
